# Default values for mongob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# mongob image URL
image: mongo:4
# To pass image pull secrets
imagePullSecrets: []



# Persistent Volume Capacity
storageCapacity: 2Gi

service:
  type: NodePort
  port: 27017
  targetPort: 27017
