apiVersion: v1
kind: Service
metadata:
  name: nodejs-guestbook-mongodb
  labels:
    app: nodejs-guestbook
    tier: db
spec:
  selector:
    app: nodejs-guestbook
    tier: db
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
