apiVersion: v1
kind: Service
metadata:
  name: nodejs-guestbook-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: nodejs-guestbook
    tier: frontend
spec:
  selector:
    app: nodejs-guestbook
    tier: frontend
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    nodePort: {{ .Values.frontend.service.nodePort }}
