apiVersion: v1
kind: Service
metadata:
  name: vue-service
  labels:
    service: vue
spec:
  selector:
    app: vue
  type: {{ .Values.vue.service.type }}
  ports:
  - port: {{ .Values.vue.service.port }}
    targetPort: {{ .Values.vue.service.port }}
